# Generated by Django 3.1.1 on 2020-10-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campuscomputing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datacentered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Esports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Securityandservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thinkcentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thinkpad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thinkstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Country', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
